### ISSUE TITLE
Cannot start service "varnish"

### ISSUE THREAD

**Issue by sanjay-thiyagarajan** [CanastaWiki/Canasta-DockerCompose#15]
```
ERROR: for varnish  Cannot start service varnish: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:75: mounting "/home/techwizzie/Open Source/Canasta/config/default.vcl" to rootfs at "/etc/varnish/default.vcl" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
```
**Steps to reproduce:**
1. Clone the official canasta repo (https://github.com/CanastaWiki/Canasta)
2. Create a docker compose file and copy the contents from [here](https://github.com/CanastaWiki/Canasta-DockerCompose/blob/main/docker-compose.yml)
3. Run ```docker-compose up```

**Comment by jeffw16** [comment]
It's not clear to me whether you copied the entire Docker Compose repo. If you didn't, that would explain why it can't find the Varnish `default.vcl` file - because it doesn't exist at the specified path!

See this isomorphic debug FAQ for details: https://canasta.wiki/faq/#there-is-some-issue-with-starting-up-the-stack-repo-as-the-database-is-complaining

**Comment by sanjay-thiyagarajan** [comment]
Yeah, copying the default.vcl file from here worked for me. Is there any reason why default.vcl is a directory in the main repo ?

**Comment by jeffw16** [comment]
It's not a directory, it's a file. It's in the stack repo rather than the Canasta image because people might need to change their `default.vcl` file to fit their wiki's specific needs.

In the future, it would be great if you could please avoid filing a bug report on the issue tracker for unsupported actions. Instead, may I suggest you send something on the Canasta mailing list? https://groups.google.com/g/canasta-wiki
