### ISSUE TITLE
switch from links to networks?

### ISSUE THREAD

**Issue by silverhikari** [CanastaWiki/Canasta-DockerCompose#31]
with links being a legacy feature of docker, i think it would be a good idea to switch from using links to using the networking feature now recommended by docker. along with doing this will remove a potential problem area as links could be removed in a newer version of docker, this would also allow for the podman engine to be used along with the main docker engine with docker-compose as at the moment podman will not run the current docker-compose file as podman does not have support for links.

**Comment by jeffw16** [comment]
I agree with the premise of this proposal, but as I understand it, this isn't really necessary for supported use cases (Podman is not supported). Currently, a default network is created for Canasta because there is no `networks:` section explicitly defined. The links are technically redundant, as they simply form aliases to the different containers. I am in favor of removing the links. The links in here are a vestige of the original Docker Compose manifest upon which Canasta's was based.

**Comment by jeffw16** [comment]
Anyway, feel free to make a PR for this

**Comment by silverhikari** [comment]
want to clarify something. the environment variables used in db, are they only used to start the mysql server or are they also needed by the web service?

**Comment by silverhikari** [comment]
well after trying a few builds it seems the only thing that needs to be changed is removing the link as it seems not need as the alias it uses is provided by the named network which is created on initialization of the docker-compose.

**Comment by silverhikari** [comment]
create pull request #32

**Comment by jeffw16** [comment]
Fixed by #32
