### ISSUE TITLE
Another Canasta Repository?

### ISSUE THREAD

**Issue by nischayn22** [CanastaWiki/Canasta-DockerCompose#7]
Hi Team,

I just saw that there's a new repository. Can I find any documentation on the reason behind this change and the differences in between these two?

Also what would be the best practice approach to pull latest changes from this repository? Are we going to maintain some versioning? Would there be certain specific tags to get the stable version of this repository and the Canasta image in general?

**Comment by jeffw16** [comment]
Good questions.

1. The reasoning for the split is summarized here: https://github.com/CanastaWiki/Canasta-Documentation#layout-of-the-project
2. If we merge #6, then it will become best practice to pull the latest version from this stack repo as much as possible. More input is needed on that from the community right now.
3. Yes, versioning exists now, as can be seen here: https://github.com/CanastaWiki/Canasta-DockerCompose/releases

Would it be possible to move the discussions on this issue to our new discussions forum on GitHub? I think this is a new feature of GitHub, so it might be better to put our discussions on there now, rather than the issues section. https://github.com/CanastaWiki/Canasta/discussions
